language: node_js
node_js:
  - node

script:
  - npm run build
  - npm run format:check
  - npm run lint:check
  - npm run coverage
  - npm run docs:check

deploy:
  provider: npm
  email: jbrown1.618@gmail.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: Ab9t8arnrVFSuxPg0xy2QJrqZ7aAluAs1+zJhgWghjF4g795Q5OKRgibNtk4+KzqSY0TfG0NQPZ+MQeEPWb2hH/ThN4VTW82lMMBFQRQ2d687tpDCbG1SahvNRFfZmU1i9FPsM9YP/Cri+wMR/YL2ScqH7Lv/1hAKEvYh07CL4deKUwV3Io6R+gPuXOzTPxzDA7mGB8ZhnbKJ+bIZkLfnAQE8Vz2kT9msPLT5W9mAEtGF8zB6aZaqjGrAPsoSN0VoSWj615gpdj6q10HGMMHrG5RT/ZjYAuzag86K7rFL1WEI5aSqkbj+yWKGw9OrBi1mxSORTd8pLFSqn0hOJcCe9JbqoDslLXTYhdRzZq9hLs3IUfSAJLqw94MDRh3gzhf61fMg8ai6uFh+bmiruewJqDz0EhyR/qb5YuDDODga4HZbnusTD1BIJNWIrKHAh3OJITnKJx7ITGZjL6u68JGqmI+3epIpnuzVgC8pI+cB3Xpdp3AIwF6XKVwAZ1EYYVSmwhqzC213THBuw+cEU/kOkGYk83MuI+9fDWoqNre9IHIF8InbHmfT+wCDNkP4yMpZndO3qdkB1zWiZnAwVqXSYrW6o9GUzxyntegfdhc80CJ6/5EK/HdOluSlpILOOxaKabcqdBsNPAlmx4mXYDuuGmdC63+wrAkxxmwKJDFYsU=
