name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install
        env:
          CI: true

      - name: Build
        run: |
          npm run build

      - name: Check
        run: |
          npm run format:check
          npm run lint:check
          npm run docs:check

      - name: Test
        run: |
          npm run coverage
        env:
          CI: true
