name: CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Checks
        env:
          CI: true
        run: |
          npm install
          npm run ci
